runtime: python311
service: default

env_variables:
  ENVIRONMENT: "prod"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always